name: Secret Test Part B

on: 
  workflow_dispatch:
    inputs:
      alias:
        description: 'Application alias'     
        required: true
      location:
        description: 'Location'     
        required: true
env:
   HERACLES_PAT: ${{ secrets.HERACLES_PAT }}
   HERACLES_LOCATION: ${{ github.event.inputs.location }}
   HERACLES_ALIAS: ${{ github.event.inputs.alias }}heracles  
job1:
    name: Build Container and push to ACR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{env.HERACLES_ALIAS}}acr.azurecr.io
        username: ${{env.HERACLES_ALIAS}}acr
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build -f acr-test/Dockerfile -t ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/acr-test:${{github.run_number}} .
        docker push ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/acr-test:${{github.run_number}}