name: Secret Test

on: 
  workflow_dispatch:
    inputs:
      alias:
        description: 'Application alias'     
        required: true
        default: 'zed'
      location:
        description: 'Location'     
        required: true
        default: 'uksouth'

env:
   HERACLES_PAT: ${{ secrets.HERACLES_PAT }}
   HERACLES_LOCATION: ${{ github.event.inputs.location }}
   HERACLES_ALIAS: ${{ github.event.inputs.alias }}heracles
     
jobs:

  job1:
    name: Create Container Registry 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        id: step1
                    
      - name: Login to Azure
        uses: azure/login@v1
        id: step2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
   
      - name: Create Container Registry
        id: step3
        run: |
                applicationName="${HERACLES_ALIAS}"
                resourceGroupName="${applicationName}-rg"
                acrName="${applicationName}acr"
                az group create -l "$HERACLES_LOCATION" --n "$resourceGroupName" 
                echo "Creating azure container registry $acrName in $resourceGroupName"
                az acr create -l $HERACLES_LOCATION --sku basic -n $acrName --admin-enabled -g $resourceGroupName -o none
  job2:
    name: Update ACR_PASSWORD secret
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - uses: actions/checkout@v2

    - id: step1
      name: Get Repo public key
      run: |
            #!/bin/sh -e
            res=$(curl --location --request GET "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets/public-key" \
               --header "Authorization: Bearer $HERACLES_PAT" \
               --header 'Cookie: logged_in=no; _octo=GH1.1.1387838137.1581271944')
            repo_public_key=$(echo $res | jq .key -r)
            repo_public_key_id=$(echo $res | jq .key_id -r)
            echo "repo_public_key=$repo_public_key" >> $GITHUB_ENV
            echo "repo_public_key_id=$repo_public_key_id" >> $GITHUB_ENV

    - id: step2
      name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - id: step3
      name: Get ACR password and Encrypt
      run: |
          #!/bin/sh -e
          npm init -y
          npm install tweetsodium
          applicationName="${HERACLES_ALIAS}"
          acrName="${applicationName}acr"
          acrUser=$(az acr credential show -n $acrName --query username -o tsv)
          acrPassword=$(az acr credential show -n $acrName --query passwords[0].value -o tsv)
          encrypted_value=$(node deployment-scripts/encrypt_secret.js "$acrPassword" "$repo_public_key")
          echo "encrypted_value=$encrypted_value" >> $GITHUB_ENV
          
    - id: step4
      name: Store Secret
      run: |
           #!/bin/sh -e
           curl_body=$(jq -n --arg key_id "$repo_public_key_id" --arg encrypted_value "$encrypted_value" '{encrypted_value: $encrypted_value, key_id: $key_id}')
           echo "CURL_BODY=$curl_body"
           curl --location --request PUT "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets/ACR_PASSWORD" \
            --header "Authorization: Bearer $HERACLES_PAT" \
            --header 'Content-Type: application/json' \
            --header 'Cookie: logged_in=no; _octo=GH1.1.1387838137.1581271944' \
            --data-raw "$curl_body"
  job3:
    name: Build Container and push to ACR
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{env.HERACLES_ALIAS}}acr.azurecr.io
        username: ${{env.HERACLES_ALIAS}}acr
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build -f acr-test/Dockerfile -t ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/acr-test:${{github.run_number}} .
        docker push ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/acr-test:${{github.run_number}}


  
  job4:
    name: Build Container and push to ACR using 'standard secret'
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: ${{env.HERACLES_ALIAS}}acr.azurecr.io
        username: ${{env.HERACLES_ALIAS}}acr
        password: ${{ secrets.MANUAL_ACR_PASSWORD }}
    - run: |
        docker build -f acr-test/Dockerfile -t ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/acr-test-manual:${{github.run_number}} .
        docker push ${{env.HERACLES_ALIAS}}acr.azurecr.io/heracles/acr-test-manual:${{github.run_number}}


  