# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          alias=$(jq .alias setup-parameters.json -r)
          echo "alias=$alias"
      - name: Run a single-line script 
        run: echo "alias=$alias"
  job1:
    runs-on: ubuntu-latest
    outputs:
      alias: ${{ steps.step1.outputs.alias }}
    steps:
    - id: step1
      run: |
            alias=$(jq .alias setup-parameters.json -r)
            echo "alias=$alias"
            echo "::set-output name=alias::$alias"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.alias}}
